-- 코드를 작성해주세요
SELECT 
II.ITEM_ID,
II.ITEM_NAME,
II.RARITY
FROM ITEM_INFO AS II
WHERE II.ITEM_ID NOT IN (SELECT PARENT_ITEM_ID AS ITEM_ID FROM ITEM_TREE WHERE PARENT_ITEM_ID IS NOT NULL GROUP BY PARENT_ITEM_ID )
ORDER BY II.ITEM_ID DESC;


# PARENT_ITEM_ID에 있지 않은 애들만 고르면 됨