-- 코드를 작성해주세요
SELECT
 ED.ID,
 CASE 
    WHEN CHILD_COUNT IS NULL THEN 0
    ELSE DD.CHILD_COUNT
END AS CHILD_COUNT
FROM ECOLI_DATA AS ED
LEFT OUTER JOIN (SELECT PARENT_ID AS ID, COUNT(PARENT_ID) AS CHILD_COUNT FROM ECOLI_DATA
GROUP BY PARENT_ID) AS DD
ON ED.ID = DD.ID
ORDER BY ED.ID ASC;