-- 코드를 입력하세요
SELECT
UG.USER_ID,
UG.NICKNAME,
(CONCAT(CONCAT(CONCAT(CONCAT(UG.CITY," ") , UG.STREET_ADDRESS1)," ") , UG.STREET_ADDRESS2)) AS 전체주소,
CONCAT(CONCAT(CONCAT(CONCAT(SUBSTR(UG.TLNO,1,3),"-"),SUBSTR(UG.TLNO,4,4)),"-"),SUBSTR(UG.TLNO,8,4)) AS 전화번호
FROM USED_GOODS_USER AS UG
WHERE UG.USER_ID IN (SELECT WRITER_ID FROM USED_GOODS_BOARD GROUP BY WRITER_ID HAVING COUNT(WRITER_ID) >= 3)
ORDER BY UG.USER_ID DESC;