-- 코드를 입력하세요
SELECT
AI.ANIMAL_TYPE,
CASE    
    WHEN AI.NAME IS NULL THEN "No name"
    ELSE AI.NAME
END AS NAME,
AI.SEX_UPON_INTAKE
FROM (SELECT ANIMAL_ID,ANIMAL_TYPE,NAME,SEX_UPON_INTAKE FROM ANIMAL_INS ORDER BY ANIMAL_ID) AS AI;

