-- 코드를 입력하세요
SELECT
CR.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR AS CR
WHERE CR.CAR_ID IN (SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
WHERE MONTH(START_DATE) = 10
)AND CAR_TYPE = '세단'
ORDER BY CR.CAR_ID DESC;