-- 코드를 입력하세요
SELECT
UG.TITLE,
UG.BOARD_ID,
UGR.REPLY_ID,
UGR.WRITER_ID,
UGR.CONTENTS,
DATE_FORMAT(UGR.CREATED_DATE,'%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD AS UG
JOIN USED_GOODS_REPLY AS UGR
ON UG.BOARD_ID = UGR.BOARD_ID
WHERE UG.CREATED_DATE BETWEEN DATE('2022-10-01') AND DATE('2022-10-31')
ORDER BY UGR.CREATED_DATE, UG.TITLE;
